### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by Zyles** [Kocal/vue-numerals#230]
`TypeError: Cannot read property 'delimiters' of undefined`

Followed the readme exactly.

**Comment by Kocal** [comment]
In Node.js or browser?

I can't reproduce the issue on Node https://codesandbox.io/s/cxyrn or browser https://codesandbox.io/s/vue-numerals-browser-tfrpi install

**Comment by Zyles** [comment]
I use it in Node with [Gridsome](https://gridsome.org/).

**Comment by Kocal** [comment]
Ok

**Comment by Zyles** [comment]
Use locale "sv" and you get the error.

**Comment by Kocal** [comment]
It is not supported by Numeral.js: https://github.com/adamwdraper/Numeral-js/tree/master/locales

So OFC it can't work.

But you can register custom locale: http://numeraljs.com/#locales
