### ISSUE TITLE
Remove insignificant trailing zeros from a number?

### ISSUE THREAD

**Issue by yohanes-ai** [Kocal/vue-numerals#283]
ex. 
var x = 1.234000 // to become 1.234;
var y = 1.234001; // stays 1.234001

I want used in 
`
<textarea tabindex="-1" disabled="" class="handsontableInput area-custom val1 text-center" style="">@{{ data.Koef | numeralFormat('0,0[.]00000') }}</textarea>
` 

I just want something like this in js
```
parseFloat(n.toFixed(4));
Number(n.toFixed(4));
```

**Comment by Kocal** [comment]
Hi, you can check which format to use on http://numeraljs.com/.
