### ISSUE TITLE
e.config.globalProperties is undefined

### ISSUE THREAD

**Issue by gianpesto** [Kocal/vue-numerals#394]
Hi,
i am using v3.0.8 in a nuxt project.
i was running npm audit fix on a project and somehow had to delete and reinstall all my node_modules. since then i was having an error during runtime that said: e.config.globalProperties is undefined.

as i can see in the 
https://unpkg.com/vue-numerals@3.0.8/dist/vue-numerals.min.js
there is no such thing as e.config.globalProperties

as in the latest
https://unpkg.com/vue-numerals@4.0.1/dist/vue-numerals.min.js
there is.

have i f*** up the versions? i cant wrap my head around what went wrong.

**Comment by Kocal** [comment]
Hi,

The line you are refering is https://github.com/Kocal/vue-numerals/blob/master/src/index.js#L12, this was added for the support of Vue 3 and released in v4.0.0.

Are you sure you are using v3.0.8?

**Comment by gianpesto** [comment]
Hi,
i have to correct myself, i upgraded to 3.1.0 and that contains the globalProperties as you can see here:
https://unpkg.com/vue-numerals@3.1.0/dist/vue-numerals.min.js

is that intended?

**Comment by Kocal** [comment]
Ah! Totally not, I failed my release and I was unable to unpublish it for an unknown reason.
I will ask to the NPM support to remove this version

**Comment by Kocal** [comment]
I've published v3.1.1 which is a "revert" of 3.1.0. It is now compatible with Vue 2 again, see https://github.com/Kocal/vue-numerals/releases/tag/v3.1.1.

**Comment by Kocal** [comment]
NPM support recommended me to deprecate 3.1.0. 
See https://www.npmjs.com/package/vue-numerals/v/3.1.0.

Closing as resolved, thanks again!
